### ISSUE TITLE
Enhancement: Logo Design

### ISSUE THREAD

**Issue by debpedrano** [abhi-r3v0/Adhrit#13]
Greetings Project Owner, 

I am a graphics designer who contributes on any Open Source projects. I saw your project that is really helpful in the community, I am interested in making a NEW LOGO..

I am asking your permission to do it.

Regards,

Deb

**Comment by abhi-r3v0** [comment]
Hi, 

Could you please ping me on Hangouts or drop me a mail @jmabhishek4@gmail.com?

**Comment by debpedrano** [comment]
sorry for replying late, I have to open this issue because I think I have to correct your logo. seems the android logo is not properly made by the old designer but I have to credit him for making a good artistic minded logo. @abhi-r3v0 , is there any chance I can make it through? I will DM you in gmail. have a nice day ahead!
