### ISSUE TITLE
Error lib32ncurses5

### ISSUE THREAD

**Issue by robdollard** [abhi-r3v0/Adhrit#24]
Hi, in case of start of a script of installer.py all packets except lib32ncurses5 it is set.
With it there is a problem he wants that I set it manually
"[!] Error installing lib32ncurses5. Please install manually: 'sudo apt-get - f install lib32ncurses5'"
I execute "sudo apt-get - f install lib32ncurses5" but the error "is displayed by E: Unable to locate package lib32ncurses5" 

I tried to add architecture of i386 but success it did not bring, everything is also displayed this error.
Os - "Linux parrot 4.19.0-parrot1-20t-amd64 #1 SMP

**Comment by veter069** [comment]
I change 'lib32ncurses5' to 'lib32ncurses6' in line 12 of installer.py work fine for me.

**Comment by abhi-r3v0** [comment]
Was actually planning to replace toolchains altogether with some better alternatives. But, this looks like a good fix for now. Thanks for reporting and finding a workaround! :+1:  :)
