### ISSUE TITLE
on running code

### ISSUE THREAD

**Issue by alokjain024** [abhi-r3v0/Adhrit#29]
ImportError: No module named smarser.parser

**Comment by abhi-r3v0** [comment]
Hi!

Thank you for pointing this out. I just noticed I haven't added the parser to the installer script.

**Comment by alokjain024** [comment]
Hey Abhi,

thanks for quick response, however you can use :

python3 adhrit.py ....

and make sure to downgrade cement framework before running script

**Comment by alokjain024** [comment]
i got running through python3 in linux
