### ISSUE TITLE
Dependency issues in Mac

### ISSUE THREAD

**Issue by gokulkrishna01** [abhi-r3v0/Adhrit#4]
Probably the `installer.py` needs a reconstruct for Mac.

**Comment by PSNAppz** [comment]
@gokulkrishna01 Can you please provide some more details on this?

**Comment by PSNAppz** [comment]
It should be `brew install` instead of `apt-get`

**Comment by the1220** [comment]
eta on fix

**Comment by PSNAppz** [comment]
@the1220 See #8 . Test it locally and let me know.
