### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [abhi-r3v0/Adhrit#9]
Good day ! can i submit my designs ?

**Comment by abhi-r3v0** [comment]
Sure! Would be great! :+1:

**Comment by loydjayme25** [comment]
sir ? do you have any perspective about the icon/logo ? so that i can adjust it and to have a better output.

**Comment by loydjayme25** [comment]
![proposal](https://user-images.githubusercontent.com/37318022/39669883-de7be8a2-512a-11e8-8c96-564090220ffc.png)

The concept of my design is a android , an arrow serves as a reverse and a clock look like design means that this is not a time consuming project.

**Comment by abhi-r3v0** [comment]
Wonderful!
@loydjayme25 this looks relevant and neat! Could you ping/mail me on Hangouts/Gmail at jmabhishek4@gmail.com so that we can discuss this further?

Thanks!

**Comment by loydjayme25** [comment]
i already sent a message sir

**Comment by abhi-r3v0** [comment]
Thanks a lot for the amazing design!
